version: '3'
services:
  mysql:
    image: dev/db
    container_name: dev_mysql
    command: 
      --sql_mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
      --lower_case_table_names=1
    ports:
      - 3306:3306
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_HOST: "%"
    
  mongo:
    image: dev/mongo
    container_name: dev_mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      
  vaccine-vendor:
    image: vaccine-vendor:latest
    container_name: vaccine-vendor
    ports:
      - "8082:8082"    
      
  patient-service:
    image: patient-service-2:latest
    container_name: patient-service-2
    ports:
      - "8081:8081" 
      
  hospital-service:
    image: hospital-service:latest
    container_name: hospital-service
    ports:
      - "8083:8083" 
    depends_on:
      - mysql

      
volumes:
  mysqldb:
  mongodb: