apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: patient-service
  name: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: patient-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: patient-service
    spec:
      containers:
        - image: patient-service-2:latest
          name: patient-service-2
          ports:
            - containerPort: 8081
          imagePullPolicy: Never
          resources: {}
      restartPolicy: Always
status: {}
